name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: true

    - name: Build Debug APK
      run: |
        export ANDROID_HOME=/usr/local/lib/android/sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        if [ -f "./gradlew" ]; then
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
        else
          gradle wrapper
          ./gradlew assembleDebug --stacktrace
        fi
        
